name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master # ドキュメントリポジトリのメインブランチにプッシュされたら実行

permissions:
  contents: write # 必須: gh-pagesブランチへの書き込み権限
  pages: write    # 必須: GitHub Pages設定を更新する権限
  id-token: write # 必須: OpenID Connect (OIDC) を使用する権限 (pagesデプロイに必要)

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs and Theme
        run: pip install mkdocs-material

      - name: Build MkDocs Site
        # ビルドを実行し、結果をデフォルトの 'site' フォルダに出力
        run: mkdocs build
        # mkdocs gh-deploy は upload と deploy を同時に行うため、
        # ここでは単に mkdocs build に変更します。

      # ★ 必須追加ステップ 1: ビルド結果をアーティファクトとしてアップロード
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3 # GitHub Pages専用のアップロードアクション
        with:
          path: 'site' # MkDocsのビルド出力先ディレクトリ

      # ★ 必須追加ステップ 2: デプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4